= Revolut Java Test
:toc:
:sectnums:

== Requirements

Design and implement a RESTful API
(including data model and the backing implementation)
for money transfers between accounts.

Explicit requirements:

. keep it simple and to the point
    (e.g. no need to implement any authentication, assume the APi is
    invoked by another internal system/service)
. use whatever frameworks/libraries you like
    (except Spring, sorry!) but don't forget about the
    requirement #1
. the datastore should run in-memory for the sake of this test
. the final result should be executable as a standalone program
    (should not require a pre-installed
    container/server)
. demonstrate with tests that the API works as expected

Implicit requirements:

. the code produced by you is expected to be of high quality.
. there are no detailed requirements, use common sense.

== Implementation Notes

=== Configuration

Limitations are present:

- No possibility to have layered overriding capabilities
    (like spring profiles)
- No dynamic parsing of config file, very manual instead
- Config file loading is ugly (singleton pattern)
- Cannot easily change property prefix for Properties objects

Considered solutions:

- hardcoded config: ugly
- properties based config manually implemented mapping to objects
    (chosen)
- snakeyaml:
    Not chosen snakeyaml because it requires the full contents of
    the yaml to map to the java class.
    Spring solves this issue somehow though.
- properties mapped to objects dynamically:
    no known solution other than spring

