= Revolut Java Test
:toc:
:sectnums:

== Requirements

Design and implement a RESTful API
(including data model and the backing implementation)
for money transfers between accounts.

Explicit requirements:

. keep it simple and to the point
    (e.g. no need to implement any authentication, assume the APi is
    invoked by another internal system/service)
. use whatever frameworks/libraries you like
    (except Spring, sorry!) but don't forget about the
    requirement #1
. the datastore should run in-memory for the sake of this test
. the final result should be executable as a standalone program
    (should not require a pre-installed
    container/server)
. demonstrate with tests that the API works as expected

Implicit requirements:

. the code produced by you is expected to be of high quality.
. there are no detailed requirements, use common sense.

== Implementation Notes

1. Decided to ignore the topic of currency conversions.
1. Using UK bank accounts (sort code, account number)

=== Dropwizard

Things I like

- Endpoint definition is like spring MVC
- Request payload validation

Things I don't like

* Logging disabled in TransferResourceIT by ResourceTestRule (wtf???)
* Need to use junit rules to boot up the framework in tests.
    This makes passing in mocks that are managed by the mockito junit runner
    impossible, forcing manual mock management
* Configuration is very basic
** No hierarchical override system
** Can't easily just 'plug into' the config and map parts to object,
    you need to map the whole file from the root to one.
    This actually isn't too bad.
* No obvious way to log http traffic in tests

=== Ratpack

I also considered using Ratpack.
In fact, I started out with it initially.
I really liked ratpack's API.

However it is not a full framework, does not offer integration with too many
things out of the box, like dropwizard does.
So I decided to swap to dropwizard.

In hindsight I don't know if it was the right decision.
The final straw with ratpack was the missing integration with hibernate validation
and no built-in alternative for validating incoming requests.

The branch for ratpack is also in this repository.